nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
npmRegistryServer: "https://art-bobcat.autodesk.com/artifactory/api/npm/team-autocad-npm-virtual"
